### ISSUE TITLE
Reported SOTA values in Table 2 ETH/UCY results

### ISSUE THREAD

**Issue by centiLinda** [MaKaRuiNah/SHENet#5]
Hi, thanks for sharing your work!

I noticed that the SOTA results in Table 2 differ from those in their original papers. For example, the average ADE in YNet was reported to be 0.18, instead of 0.24.

Are those values derived from your local implementation? Is it because you used a smaller set in UNIV?

It makes perfect sense that you didn't use their reported values directly, since you're working on a slightly different dataset. But I just wonder why the performance drops (for AgentFormer and YNet for example) when you use a smaller set in UNIV?

**Comment by MaKaRuiNah** [comment]
Regarding the observed differences in performance drops compared to the original papers, we believe there are two main factors contributing to these variations: 1) reproduction in different environments: in our implementation, we reproduce the baseline results in our own environment, which may differ from the original authors' code environments. 2) utilization of a smaller dataset subset: specifically in our case, the UNIV set.

**Comment by fyangneil** [comment]
> Regarding the observed differences in performance metrics compared to the original papers, we believe there are two main factors contributing to these variations: 1) reproduction in different environments: in our implementation, we reproduce the baseline results in our own environment, which may differ from the original authors' code environments. 2) utilization of a smaller dataset subset: specifically in our case, the UNIV set.

@centiLinda

**Comment by centiLinda** [comment]
Thanks for your reply and I agree with both of your points. I just feel that there's a lack of unified evaluation guidelines for ETH/UCY dataset, although its been commonly used in trajectory prediction.

- For example there's a wrong sampling issue on the ETH subset: https://github.com/cocoon2wong/Vertical/issues/1
- All works that use images have to use a smaller set in UNIV (like yours).
- More importantly the trajectory selection process (during preprocessing) is very different in different open-source works that I've seen. This results in different number of datapoints used for training.

It makes more sense to reproduce baseline results locally (like what you choose to do), so all methods use the same raw data with the same preprocessing methods. But some people might argue, especially when the performance drops in your local implementation, that the baseline methods are not reproduced/fine-tuned properly.

Just sharing some of my thoughts. Thanks again for sharing your work!
