### ISSUE TITLE
Pre-trained Swin Transformer

### ISSUE THREAD

**Issue by centiLinda** [MaKaRuiNah/SHENet#7]
Hi author,

I noticed this is where you load the pre-trained model:
https://github.com/MaKaRuiNah/SHENet/blob/995599b8a5f037505c9310003801cf5d7209720a/utils/parser.py#L28-L29

Is it also uploaded to your Baidu Drive? (I haven't downloaded your full model yet, coz I'm having trouble accessing Baidu Drive)

Which pre-trained Swin Transformer did you use? Could you share the GitHub link where you downloaded it?

Thank you!

**Comment by MaKaRuiNah** [comment]
We utilized the segmentation model from the mmsegmentation library. You can download the pretrained model by visiting the [URL](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/swin/README.md). @centiLinda

**Comment by centiLinda** [comment]
I see, thank you!
